### ISSUE TITLE
Version conflict for meson : 0.56.0 vs 0.56.2

### ISSUE THREAD

**Issue by Mutos** [naev/naev#1685]
Hello all,

I catched up on **_master_** branch on my local repo after months, and tried to compile for Linux (Ubuntu 20.04.1 LTS), but now I got the following error with **_meson_** not being at the right version : 

`pkg_resources.VersionConflict: (meson 0.56.2 (/home/leschouchous/.local/lib/python3.8/site-packages), Requirement.parse('meson==0.56.0'))`

I've searched the net for a solution, including meson docs, but for now to no avail. My meson version is 0.56.2 but it seems there is somewhere something strictly specifying a 0.56.0 version... The only reference to a meson version I found is in **_meson.build_** and it's not that restrictive : 
`meson_version: '>=0.55.0'`

I've also checked the **_/usr/lib/python3/dist-packages/pkg_resources/__init__.py_** file quoted in the error stack, but there is no meson version in it...

Thanks a lot for any hint !

Benoît 'Mutos' Robin

PS : the full error stack is the following : 

```
$ meson setup bin/lin64/ .
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (meson 0.56.2 (/home/leschouchous/.local/lib/python3.8/site-packages), Requirement.parse('meson==0.56.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'meson==0.56.0' distribution was not found and is required by the application
```

**Comment by UncombedCoconut** [comment]
I've never seen this before, but I see from the error message is coming from `/usr/local/bin/meson` as it loads Meson's Python modules from `/home/leschouchous/.local/lib/python3.8/site-packages`.
I suspect this means you have local Meson installations in both places, and at least one of them needs to go.
(I'm not sure how to remove one, and it probably depends on how it was originally installed.)

**Comment by Mutos** [comment]
Hi @UncombedCoconut,

Thanks, that's a good remark, I'll try this path and tell you if it goes somewhere !

@+

Benoît 'Mutos' Robin

**Comment by Mutos** [comment]
Hi @UncombedCoconut,

It works ! I removed the meson file and reinstalled meson by apt-get, and it worked directly...

Thanks a lot for the little hint that unlocked everything !

Benoît 'Mutos' Robin
