### ISSUE TITLE
[Bug]: SIGSEGV at leaving the Unusual Derelict in a sensor anomaly event.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2604]
### What happened?

I solved a pazzle and got an award and SIGSEGV.

The first bad commit may be b024d8c9363ff3ffb5b8f9bd791a065ebb1af656.

### Version

008d8c9ed1 (Current main, local build)

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Back trace:

Thread 1 "naev" received signal SIGSEGV, Segmentation fault.
0x00007ffff79b184f in lua_setfenv ()
   from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
(gdb) bt
#0  0x00007ffff79b184f in lua_setfenv ()
   from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#1  0x00005555556411e3 in nlua_pcall (env=12498, nargs=nargs@entry=5, 
    nresults=nresults@entry=0) at ../src/nlua.c:987
#2  0x00005555556df349 in spfxL_renderLayer (func=func@entry=2, 
    funcname=funcname@entry=0x55555570007b "rendermg", dt=dt@entry=0)
    at ../src/nlua_spfx.c:750
#3  0x00005555556dfe34 in spfxL_renderfg (dt=dt@entry=0)
    at ../src/nlua_spfx.c:785
#4  0x000055555569e6de in spfx_render (layer=layer@entry=0, dt=dt@entry=0)
    at ../src/spfx.c:1177
#5  0x000055555567fa7b in render_all (game_dt=<optimized out>, 
    real_dt=0.016528834999999999) at ../src/render.c:230
#6  0x000055555559c64f in main_loop (nested=nested@entry=0)
    at ../src/naev.c:833
#7  0x000055555559d3ca in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/naev.c:494
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report. I don't really understand why it is crashing, will have to look at it into more detail. However, I've undone the environment changes for now, as they most likely should not be necessarily anyways. Thanks!
